### ISSUE TITLE
Warn when emitting an event from a view function

### ISSUE THREAD

**Issue by milancermak** [crytic/amarna#44]
I'd like to suggest a new rule:

There should be a warning if an [event](https://www.cairo-lang.org/docs/hello_starknet/events.html) is being emitted from a `@view` function.

Granted, the rule is somewhat subjective, but I don't see a point in emitting from a `@view`. WDYT?

**Comment by fcasal** [comment]
Hi @milancermak , this makes sense because emitting an event causes a state change. This will be addressed in a future iteration of https://github.com/crytic/amarna/pull/42
