### ISSUE TITLE
Don't warn about overflows on const values

### ISSUE THREAD

**Issue by milancermak** [crytic/amarna#53]
If possible, it would be great to avoid false positives when detecting potential overflows like this one on the screenshot

<img width="730" alt="Screenshot 2022-07-25 at 17 13 54" src="https://user-images.githubusercontent.com/184055/180813554-af1ef357-2363-4f2f-aa0f-2fdf18b44368.png">

It's clear that `8000 * 5` is a constant value that fits inside a `felt`, there's no overflow hazard.

Here's a gif of a dachshund kissing a lion for no particular reason

![](https://media.giphy.com/media/jY158IeKtcVAQ/giphy.gif)

**Comment by fcasal** [comment]
As always, thanks for the rule improvement suggestions!
