### ISSUE TITLE
Cairo 0.9.1 support

### ISSUE THREAD

**Issue by ca11ab1e** [crytic/amarna#66]
[Cairo 0.9.1](https://github.com/starkware-libs/cairo-lang/releases/tag/v0.9.1) introduced support for `and` in `if` statements (`if x == y and z == w`). And running Amarna on a contract using such statement will fail:

```
Could not parse contract.cairo: Unexpected token Token('IDENTIFIER', 'and') at line 1158, column 31.
Expected one of: 
        * LBRACE
        * DOT
        * SLASH
        * LPAR
        * LSQB
        * MINUS
        * COLON
        * STAR
        * PLUS
        * _DBL_STAR
```

**Comment by ca11ab1e** [comment]
Wow you were blazing fast, thanks!

**Comment by coolhill** [comment]
This will make it into a release on PyPi soon enough. For now you can install the latest amarna version from the repo manually:
```bash
git clone https://github.com/crytic/amarna.git && cd amarna
pip install -e .
```

**Comment by ca11ab1e** [comment]
Tested, and I confirm the fix works :+1:
