### ISSUE TITLE
zsh: command not found: amarna

### ISSUE THREAD

**Issue by yettaahhhh** [crytic/amarna#70]
I installed amarna globally on MacOS, and `pip freeze` shows that the package has been installed successfully, yet CLI shows `zsh: command not found: amarna` when using the command.

**Comment by coolhill** [comment]
As a potential work-around, try installing it in a python virtual environment;
```
$ python3.7 -m venv ~/amarna_venv
$ source ~/amarna_venv/bin/activate
$ pip install amarna
```

**Comment by fcasal** [comment]
Closing for now.
