### ISSUE TITLE
False positives in @contract_interface

### ISSUE THREAD

**Issue by milancermak** [crytic/amarna#83]
Consider this interface declaration (a simplified version of [this one](https://github.com/BibliothecaForAdventurers/realms-contracts/blob/main/contracts/settling_game/interfaces/imodules.cairo)):

```cairo

@contract_interface
namespace IModuleController {
    func set_write_access(module_id_doing_writing: felt, module_id_being_written_to: felt) {
    }
}
```

Amarna produces 2 false positives - unused argument (for both arguments) and function never called.

<img width="1159" alt="Screenshot 2022-10-11 at 21 15 42" src="https://user-images.githubusercontent.com/184055/195179939-ab75558d-1d40-4616-8ceb-a301b6ea9b4c.png">

Of course, neither make sense in a `@contract_interface` declaration.

**Comment by fcasal** [comment]
Thanks for reporting this, namespace decorators weren't being propagated
