### ISSUE TITLE
Don't flag constructor as never called

### ISSUE THREAD

**Issue by milancermak** [crytic/amarna#9]
I've enabled Amarna on one of my Cairo repos. It flagged an issue that `@constructor` is never called (even though the repo is [public](https://github.com/milancermak/cairo-4626) I don't think I can link directly to the static analysis issue so here's a screenshot):

<img width="971" alt="Screenshot 2022-04-21 at 10 25 16" src="https://user-images.githubusercontent.com/184055/164413155-3b19b9aa-d525-41c0-9f8b-de5f342d3521.png">

I would say this rule should be disabled for `@constructor`s.

**Comment by milancermak** [comment]
Amarna will actually flag `@view` and `@external` functions as unused as well.

**Comment by fcasal** [comment]
Hi @milancermak, thanks for reporting this. I've fixed the @constructor false positive in https://github.com/crytic/amarna/commit/42b5ddddbdb45847d40d310331a4c7dfa2bad1b2. Regarding the view and external functions, running Amarna on your repo only shows `Ownable_get_owner` and `Ownable_transfer_ownership`, and neither of them are @view or @external. Do you have another codebase where this happens?

**Comment by milancermak** [comment]
Thanks for fixing the `@constructor`.

I added Amarna to another repo and thought I had a false positive there as well, but looking it now, it was also a constructor. I got my line numbers wrong.

**Comment by fcasal** [comment]
Thanks for looking into it!
